name: libcellml-upload-on-release

on:
  push


jobs:
  test-multiline:
    runs-on: macos-12

    steps:
    - name: Create files
      shell: bash
      run: |
        mkdir dist
        touch dist/release.txt
        touch dist/production.txt

    - name: Package
      id: package
      shell: cmake -P {0}
      run: |
        file(GLOB _DIST_FILES dist/*)
        string(REPLACE ";" "%0A" _DIST_FILES "${_DIST_FILES}")
        execute_process(
          COMMAND echo "::set-output name=files::${_DIST_FILES}")

    -name: Publish alternate
      uses: meeDamian/github-release@2.0
      with:
      tag_name: v0.2.0-dev.22
      token: ${{ secrets.GITHUB_TOKEN }}
      files: |
        ${{ steps.package.outputs.files }}

    - name: Publish libraries
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.2.0-dev.22
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ${{ steps.package.outputs.files }}

