name: libcellml-deploy-on-release

on:
  push

env:
  BUILD_TYPE: Release
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install libcellml
    - name: Investigate I
      if: matrix.os == 'macos-latest'
      run: |
        ls /Library/Frameworks
        ls -l /Library/Frameworks/Python.framework/Versions/
        ls -l /usr/local/Frameworks/Python.framework/Versions/
        echo "find_package(Python)" > test.cmake
        cmake -P test.cmake
    - name: Investigate II
      if: matrix.python-version == '3.8' && matrix.os == 'macos-latest'
      run: |
        install_name_tool -delete_rpath /Library/Frameworks /Users/runner/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/libcellml/_analyser.so
        otool -L /Users/runner/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/libcellml/_analyser.so
        otool -l /Users/runner/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/libcellml/_analyser.so | grep -A3 RPATH
        [ -e /Library/Frameworks/Python.framework/Versions/3.8/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /usr/local/Frameworks/Python.framework/Versions/3.8/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /opt/homebrew/Frameworks/Python.framework/Versions/3.8/Python ] && echo "exists" || echo "doesn't exist"
        echo "done."
        install_name_tool -add_rpath /usr/local/Frameworks/. /Users/runner/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/libcellml/_analyser.so
        python --version
    - name: Investigate III
      if: matrix.python-version == '3.9' && matrix.os == 'macos-latest'
      run: |
        install_name_tool -delete_rpath /Library/Frameworks /Users/runner/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/libcellml/_analyser.so
        otool -L /Users/runner/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/libcellml/_analyser.so
        otool -l /Users/runner/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/libcellml/_analyser.so | grep -A3 RPATH
        [ -e /Library/Frameworks/Python.framework/Versions/3.9/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /usr/local/Frameworks/Python.framework/Versions/3.9/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /opt/homebrew/Frameworks/Python.framework/Versions/3.9/Python ] && echo "exists" || echo "doesn't exist"
        echo "done."
        ls -lh /usr/local/Frameworks/Python.framework
        # install_name_tool -add_rpath /usr/local/Frameworks/. /Users/runner/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/libcellml/_analyser.so
        python --version
    - name: Investigate IV
      if: matrix.python-version == '3.10' && matrix.os == 'macos-latest'
      run: |
        # install_name_tool -delete_rpath /Library/Frameworks /Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/libcellml/_analyser.so
        otool -L /Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/libcellml/_analyser.so
        otool -l /Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/libcellml/_analyser.so | grep -A3 RPATH
        [ -e /Library/Frameworks/Python.framework/Versions/3.10/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /usr/local/Frameworks/Python.framework/Versions/3.10/Python ] && echo "exists" || echo "doesn't exist"
        [ -e /opt/homebrew/Frameworks/Python.framework/Versions/3.10/Python ] && echo "exists" || echo "doesn't exist"
        echo "done."
        # install_name_tool -add_rpath /usr/local/Frameworks/. /Users/runner/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/libcellml/_analyser.so
        python --version
    - name: Test libcellml
      run: |
        python -c "import libcellml;print(libcellml.versionString())"

