name: libcellml-deploy-on-release

on:
  push

env:
  BUILD_TYPE: Release
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Build
      run: |
        ls -lh
        cmake -S l1bcellml -B build-libcellml -G Ninja
        make -j4
    - name: Investigate I
      run: |
        echo "find_package(Python)" > test.cmake
        cmake -P test.cmake
    - name: Investigate II
      run: |
        otool -L build-libcellml/src/bindings/python/libcellml/_analyser.so
        otool -l build-libcellml/src/bindings/python/libcellml/_analyser.so | grep -A3 RPATH
        python --version
    - name: Test libcellml
      run: |
        python -c "import libcellml;print(libcellml.versionString())"

