on: [pull_request]

jobs:
  emscripten:
    name: libcellml.js
    runs-on: macos-latest
    steps:
      - name: Checkout libCellML
        uses: actions/checkout@v2
        with:
          repository: hsorby/libcellml
          path: libcellml
          ref: emscripten

      - name: Prepare environment for uploading assets
        shell: bash
        run: |
          pwd
          ls -A libcellml/.github/scripts
          cat /Users/runner/work/l1bcellml/l1bcellml/libcellml/.github/scripts/upload-asset.js
          cd $GITHUB_WORKSPACE/libcellml/.github/scripts/
          npm install mime
          ls -A 
      
      - name: Run script requiring mime package
        uses: actions/github-script@v3
        with:
          script: |
            console.log(process.env.PWD)
            console.log('===== This will need to change when the javascript bindings are properly added the cellml/libcellml repo. =====')
            console.log(`${process.env.GITHUB_WORKSPACE}/libcellml/.github/scripts/upload-asset.js`)
            const script = require(`${process.env.GITHUB_WORKSPACE}/libcellml/.github/scripts/upload-asset.js`)
            script({github, context})
      
      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: OpenCMISS-Dependencies/zlib
          path: zlib
          ref: develop

      - name: Checkout LibXml2
        uses: actions/checkout@v2
        with:
          repository: OpenCMISS-Dependencies/libxml2
          path: libxml2
          ref: v2.9.6

      - name: Instal emscripten
        shell: bash
        run: |
          brew install emscripten

      - name: Build and instal zlib
        shell: bash
        run: |
          mkdir build-zlib-release
          cd build-zlib-release
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../usr/local ../zlib/
          make -j3 install
          
      - name: Build and instal libXml2
        shell: bash
        run: |
          mkdir build-libxml2-release
          cd build-libxml2-release
          emcmake cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../usr/local -DZLIB_DIR=../usr/local/share/cmake/ZLIB/ -DCMAKE_PREFIX_PATH=../usr/local -DBUILD_SHARED_LIBS=OFF ../libxml2/
          make -j3 install
          
      - name: Build libcllml.js
        shell: bash
        run: |
          mkdir build-libcellml-release
          cd build-libcellml-release
          emcmake cmake -DLibXml2_DIR=../usr/local/share/cmake/LibXml2/ -DBUILD_TYPE=Release ../libcellml/
          make -j3
          
      - name: Pack libcellml.js
        shell: bash
        run: |
          cd build-libcellml-release/src/bindings/javascript
          npm pack
          ls
