on: [push, pull_request]

jobs:
  emscripten:
    name: libcellml.js
    runs-on: macos-latest
    steps:
      - name: Checkout libCellML
        uses: actions/checkout@v2
        with:
          repository: hsorby/libcellml
          path: libcellml
          ref: emscripten

      - name: Checkout zlib
        uses: actions/checkout@v2
        with:
          repository: OpenCMISS-Dependencies/zlib
          path: zlib
          ref: v1.2.3

      - name: Checkout LibXml2
        uses: actions/checkout@v2
        with:
          repository: OpenCMISS-Dependencies/libxml2
          path: libxml2
          ref: v2.9.6

