name: libcellml-deploy-on-release

on:
  push

env:
  BUILD_TYPE: Release
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest]
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Download
      run: |
        wget https://github.com/hsorby/l1bcellml/suites/8300282099/artifacts/364084197
        cmake --version
    - name: Unzip
      run: |
        unzip artifact.zip
    - name: Investigate I
      run: |
        echo "find_package(Python)" > test.cmake
        cmake -P test.cmake
    - name: Investigate II
      run: |
        echo "investigate II"
        python --version
    - name: Investigate III
      run: |
        echo "investigate III"
        ls -lh /usr/local/opt
    - name: Test libcellml
      run: |
        pip install libcellml-cp39*.whl
        python -c "import libcellml;print(libcellml.versionString())"

