name: wheels

on:
  push
#    types:
#      - published
#  workflow_dispatch:

jobs:
  wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - name: 'Windows wheels'
#            os: windows-2019
          - name: 'Linux wheels'
            os: ubuntu-20.04
#          - name: 'macOS wheels'
#            os: macos-12
    steps:
      - name: Check out libCellML
        uses: actions/checkout@v2
      - name: Configure MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.8.1
      - name: Patch cibuildwheel
        if: runner.os == 'NotLinux'
        run: |
          ls
          echo "ooooooooooooo"
          echo ${{ runner.os }}
          target=`python -c "import cibuildwheel;print(cibuildwheel.__file__.replace('__init__', 'linux'))"`
          gist_hash=a5916204d59abeb7f214e5383434daf1
          curl -L https://gist.githubusercontent.com/hsorby/$gist_hash/raw/patch_cibuildwheel_linux.py > patched_cibuildwheel_linux.py
          cp patched_cibuildwheel_linux.py $target
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse --config-file {package}/src/bindings/python/pyproject.toml
#        working-directory: src/bindings/python
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: auto64
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BUILD: cp39-*
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BEFORE_BUILD_LINUX: ls && ls .. && ls ../.. && ls ../../..
          CIBW_BEFORE_ALL_LINUX: yum install -y libxml2-devel && yum search python | grep devel
          CIBW_BEFORE_ALL_WINDOWS: cmake -S wheel -B build-wheel -G Ninja && cd build-wheel && ninja
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=11.0
#            _PYTHON_HOST_PLATFORM=macosx-11-x86_64
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./src/bindings/python/wheelhouse/*.whl
