name: wheels

on:
  push
#    types:
#      - published
#  workflow_dispatch:

jobs:
  wheels:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows wheels'
            os: windows-2019
          - name: 'Linux wheels'
            os: ubuntu-20.04
          - name: 'macOS wheels'
            os: macos-11
    steps:
      - name: Check out libCellML
        uses: actions/checkout@v2
      - name: Configure MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.8.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        working-directory: src/bindings/python
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: auto64
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BUILD: cp39-*
          CIBW_BEFORE_ALL_LINUX: yum install -y libxml2-devel
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_ENVIRONMENT_MACOS: >
            _PYTHON_HOST_PLATFORM=macosx-10.15-x86_64
          MACOSX_DEPLOYMENT_TARGET: 10.15
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./src/bindings/python/wheelhouse/*.whl
