name: wheels

on:
  push
  release:
    types:
      - created


jobs:
  wheels:
    name: ${{ matrix.name }} ${{ matrix.py }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2019]
        py: ['3.7', '3.8', '3.9', '3.10']
        include:
          - name: 'Windows'
            os: windows-2019
          - name: 'Linux'
            os: ubuntu-20.04
          - name: 'macOS'
            os: macos-12
        exclude:
          - os: macos-12
            py: '3.7'
          - os: macos-12
            py: '3.8'
    steps:
      - name: Check out libCellML
        uses: actions/checkout@v2
      - name: Setup for cibuildwheel
        id: setup
        shell: bash
        run: |
          mkdir src/bindings/python/libcellml
          v=${{ matrix.py }}
          echo "Setting tag as: TAG=${GITHUB_REF#refs/tags/}"
          #echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::v0.2.0-dev.21
          echo "Setting build as: BUILD=cp${v/./}-*"
          echo ::set-output name=BUILD::cp${v/./}-*
      - name: Determine release type
        id: release
        shell: bash
        run: |
          s=${{ github.event.release.prerelease }}
          echo "this: $s"
          exit 32
      - name: Configure MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.8.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse src/bindings/python/
        env:
#          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: auto64
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BUILD: ${{ steps.setup.outputs.build }}
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BEFORE_ALL_LINUX: yum install -y libxml2-devel || (apk add libxml2-dev && rm /usr/lib/cmake/libxml2/libxml2-config.cmake)
          CIBW_BEFORE_ALL_WINDOWS: cd src/bindings/python && cmake -S wheel_dependencies -B build-wheel_dependencies -G Ninja && cd build-wheel_dependencies && ninja
          CIBW_ENVIRONMENT: LIBCELLML_VERSION_TAG=${{ steps.setup.outputs.tag }}
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=11.0
            LIBCELLML_VERSION_TAG=${{ steps.setup.outputs.tag }}
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
